WebApplication/WebApplication/ViewComponents/FooterViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebApplication.DAL;
using WebApplication.ViewModel;

namespace WebApplication.ViewComponents
{
    public class FooterViewComponent:ViewComponent
    {
        private AppDbContext _context;

        public FooterViewComponent(AppDbContext context)
        {
            _context = context;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            FooterViewModel footerViewModel = new FooterViewModel
            {
                Services = await _context.Services.ToListAsync(),
                Companies=await _context.Companies.ToListAsync(),
                SocialMedias=await _context.SocialMedias.ToListAsync()
            };
            return View(footerViewModel);
        }
    }
}

WebApplication/WebApplication/ViewComponents/HeaderViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebApplication.DAL;
using WebApplication.Models.Home;
using WebApplication.ViewModel;

namespace WebApplication.ViewComponents
{
    public class HeaderViewComponent:ViewComponent
    {
        private AppDbContext _context;

        public HeaderViewComponent(AppDbContext context)
        {
            _context = context;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            List<BasketViewModel> basket;
            if (Request.Cookies["basket"] != null)
            {
                basket = JsonConvert.DeserializeObject<List<BasketViewModel>>(Request.Cookies["basket"]);
                ViewBag.BasketItemCount = basket.Count();
            }
            else
            {
                ViewBag.BasketItemCount = 0;
            }
            var setting = _context.Settings.AsEnumerable().ToDictionary(s => s.Key, s => s.Value);
            return View(await Task.FromResult(setting));
        }
    }
}

WebApplication/WebApplication/Views/Shared/_Layout.cshtml
@using WebApplication.Services
@inject LayoutServices service
@{
    Dictionary<string, string> setting = service.GetSetting();
}



<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link rel="icon" href="~/img/favicon.png" sizes="192x192" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="~/owlcarousel/owl.carousel.min.css">
    <link rel="stylesheet" href="~/owlcarousel/owl.theme.default.min.css">
    <link rel="stylesheet" href="~/css/style.css">
    <title>Fiorello &#8211; @ViewData["Title"]</title>
</head>

<body>

    @await Component.InvokeAsync("Header")    

    @RenderBody()
    <footer>
        <div class="container">
            <div class="row py-5">
                @await Component.InvokeAsync("Footer")
                <div class="col-md-6 col-lg-3">
                    <div class="item">
                        <h6>ARCHIVE</h6>
                        <ul class="list-unstyled mt-4">
                            <li><a class="text-black-50" href="">Designer Shoes</a></li>
                            <li><a class="text-black-50" href="">Gallery</a></li>
                            <li><a class="text-black-50" href="">Pricing</a></li>
                            <li><a class="text-black-50" href="">Feature Index</a></li>
                            <li><a class="text-black-50" href="">Login</a></li>
                            <li><a class="text-black-50" href="">Help & Support</a></li>
                        </ul>
                    </div>
                </div>
            </div>

            <hr>

            <div class="row py-2">
                <div class=" col-lg-4 text-center text-lg-left">
                    <p class="text-black-50">
                        Powered by <a class="author text-muted"
                                      href="https://www.bakhtiyar.az">Bakhtiyar Shamilzada</a> 2020
                    </p>
                </div>
                <div class=" col-lg-4 text-center">
                    <img src="~/img/footer-bottom-1.png" class="fluid" alt="">
                </div>
                <div class=" col-lg-4 text-center text-lg-right mt-3 mt-lg-0">
                    <a class="text-black-50 mr-5"
                       href="https://www.linkedin.com/in/bakhtiyar-shamilzada-145159185/">LINKEDIN</a>
                    <a class="text-black-50" href="https://www.facebook.com/shamilzada.bakhtiyar">FACEBOOK</a>
                </div>
            </div>
        </div>
    </footer>

    <!-- FOOTER END -->

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
            integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
            crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
            integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
            integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
            crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/e5e249fce2.js" crossorigin="anonymous"></script>
    <script src="~/owlcarousel/owl.carousel.min.js"></script>
    <script src="~/js/script.js"></script>
</body>

</html>

WebApplication/WebApplication/Views/Shared/_ProductPartial.cshtml
@model IEnumerable<Product>
@foreach (var pro in Model)
{
    <div class="col-sm-6 col-md-4 col-lg-3 mt-3">
        <div class="product-item text-center">
            <div class="img">
                <a asp-action="Detail" asp-route-id="@pro.Id">
                    <img src="~/img/@pro.Images.Where(i=>i.IsMain==true).FirstOrDefault().Image" class="img-fluid" alt="">
                </a>
            </div>
            <div class="title mt-3">
                <h6>@pro.Name</h6>
            </div>
            <div class="price">
                <span class="text-black-50">Add to cart</span>
                <span class="text-black-50">$@pro.Price</span>
            </div>
        </div>
    </div>
}